name: Test Project
on: [push]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Get code
      uses: actions/checkout@v4
    
    - name: Install node js
      uses: actions/setup-node@v4
      with:
        node-version: 18
    
    - name: Install depedencies
      run: npm ci

    - name: Run tests
      run: npm test

  deloy:
    needs: test
    runs-on: self-hosted
    steps:
    - name: Get code
      uses: actions/checkout@v4
    
    - name: Install node js
      uses: actions/setup-node@v4
      with:
        node-version: 18
    
    - name: Install depedencies
      run: npm ci

    - name: Build project
      run: npm run build
    
    - name: Deploy
      run: echo "Deploying ..."
    
    - name: test-aws
      run: which aws